# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'ProjectBase-Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ProjectBase-Demo
  pod 'MJRefresh'
  pod 'DZNEmptyDataSet'
  pod 'SnapKit'
  pod 'Hue'
  
end
